title: Rahil Tech Hacks
description: "Your source for programming tutorials, hacking tips, and tech guides."
theme: minima
baseurl: "/rahil-tech-hacks" # Change this to your repository name
url: "https://username.github.io" # Replace with your GitHub username
author: Shahid Bashir
emil: GeekOwl 

# Social Links (Optional)
social_links:
youtube: "https://youtube.com/@rahil_tech_hacks?si=gqnaBfRpyRj3ftDa/UCg3CbOCbETw3di4Kco1sKdQ"
  github: "https://github.com/rahildarc"
  twitter: "https://twitter.com/your-twitter-handle"

# Plugins (Optional)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
