title: "Rahil Tech Hacks"
description: "Your source for programming tutorials, hacking tips, and tech guides."
theme: minima
baseurl: "/rahil-tech-hacks"
url: "https://username.github.io/rahil-tech-hacks"

author: "Shahid Bashir"
email: "your-email@example.com"

social_links:
  youtube: "https://www.youtube.com/channel/your-channel-id"
  github: "https://github.com/username"
  twitter: "https://twitter.com/your-twitter-handle"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
